spring:
  application:
    name: Backend

  datasource:
    url: jdbc:mysql://localhost:3306/phoneshop
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"
